version: "3.9"

# 2 services web (the application) and mysql (mysql image)
services:

  mysql_db:
    image: mysql
    container_name: mysql-db
    networks:
      - jwt
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  web :
    build: .
    networks:
      - jwt
    ports:
      - "6868:8080"
    container_name: back-jwt
    depends_on:
      mysql_db:
        condition: service_healthy

networks:
  jwt:
    name : jwt-network
    ipam:
      #driver: bridge
      config:
        - subnet: 172.16.238.0/24